import { MovingRectangleBackground } from "src/app/shared/model/displayValues/general";

export const CardsBackgroundInfos: MovingRectangleBackground[] = [
    {
        originalTop: 15,
        top: 15,
        width: 55,
        left: 5,
        originalLeft: 5,
        height: 80,
        color: "var(--mainColor)",
        movingSide: false,
        movingSpeed: 80,
    },
    {
        originalTop: 33,
        top: 53,
        width: 50,
        left: 52,
        originalLeft: 52,
        height: 71,
        color: "var(--mainColor)",
        movingSide: true,
        movingSpeed: -15,
    },
    {
        originalTop: 106,
        top: 106,
        width: 12,
        left: 10,
        originalLeft: 45,
        height: 45,
        color: "var(--secondColor)",
        movingSide: true,
        movingSpeed: 36,
    },
    {
        originalTop: 134,
        top: 134,
        width: 81,
        left: 4,
        originalLeft: 17,
        height: 76,
        color: "var(--mainColor)",
        movingSide: false,
        movingSpeed: 85,
    },
    {
        originalTop: 270,
        top: 270,
        width: 72,
        left: 30,
        originalLeft: 30,
        height: 85,
        color: "var(--mainColor)",
        movingSide: true,
        movingSpeed: -10,
    },
    {
        originalTop: 262,
        top: 262,
        width: 7,
        originalLeft: 7,
        left: 8,
        height: 65,
        color: "var(--secondColor)",
        movingSide: false,
        movingSpeed: -82,
    },
    {
        originalTop: 316,
        top: 316,
        width: 75,
        originalLeft: 23,
        left: 23,
        height: 75,
        color: "var(--mainColor)",
        movingSide: false,
        movingSpeed: 75,
    },
    {
        originalTop: 370,
        top: 370,
        width: 8,
        originalLeft: 78,
        left: 78,
        height: 35,
        color: "var(--secondColor)",
        movingSide: true,
        movingSpeed: -33,
    },
    {
        originalTop: 420,
        top: 420,
        width: 80,
        originalLeft: 0,
        left: 0,
        height: 90,
        color: "var(--mainColor)",
        movingSide: true,
        movingSpeed: -13,
    },
    {
        originalTop: 510,
        top: 510,
        width: 8,
        originalLeft: 78,
        left: 78,
        height: 35,
        color: "var(--secondColor)",
        movingSide: false,
        movingSpeed: -85,
    },
]